# Generated by Django 6.0 on 2025-12-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('USER', 'User'), ('DOCTOR', 'Doctor'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='USER', max_length=10),
        ),
    ]
