# Generated by Django 6.0 on 2025-12-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='consultation_type',
            field=models.CharField(choices=[('ONLINE', 'Online Consultation'), ('CLINIC', 'Clinic Consultation')], default='ONLINE', max_length=10),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='BOOKED', max_length=20),
        ),
    ]
