# Generated by Django 6.0 on 2025-12-31 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_amount_appointment_consultation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_mode',
            field=models.CharField(choices=[('ONLINE', 'Online Payment'), ('PAY_AT_CLINIC', 'Pay at Clinic')], default='PAY_AT_CLINIC', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('BOOKED', 'Booked'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='BOOKED', max_length=20),
        ),
    ]
