# Generated by Django 6.0 on 2026-03-10 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_appointment_age_appointment_current_health_problem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='previous_health_problem',
            new_name='health_history',
        ),
    ]
