# Generated by Django 6.0 on 2026-06-07 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_rename_previous_health_problem_appointment_health_history'),
        ('doctors', '0006_alter_doctor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='current_health_problem',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='gender',
            new_name='contact_number',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='health_history',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='whatsapp_number',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='slot_type',
            field=models.CharField(default='ONLINE', max_length=10),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.timeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('doctor', 'date', 'start_time', 'end_time')},
        ),
    ]
