# Generated by Django 6.0 on 2025-12-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_experience_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='is_active',
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
