# Generated by Django 6.0 on 2025-12-22 14:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0004_doctor_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeslot',
            old_name='time',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='doctors.doctor'),
        ),
    ]
