# Generated by Django 6.0 on 2026-01-02 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointmentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(default=datetime.date(2026, 1, 2)),
            preserve_default=False,
        ),
    ]
