# Generated by Django 6.0 on 2026-01-03 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_appointment_booked_by_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointment_date',
        ),
    ]
